config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :admins
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'about_2nd_fridays', to: 'pages#about_2nd_fridays'
  get 'funding', to: 'pages#funding'

  get 'pages/events'
  get 'pages/event_1'
  get 'pages/exhibitions'
  get 'pages/exhibition'
  get 'pages/calendar'
  get 'pages/calendar_all'

  get 'galleries/alumni_galleries'

  resources :galleries do
    collection { post :import}
  end 
  resources :exhibitions do
    collection { post :import}
  end
  resources :events do
    collection { post :import}
    member do
      post :participation
    end
  end
  resources :participations

  root 'pages#home'

end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
  has_many :images

  belongs_to :gallery
  validates :gallery, presence: true

  scope :current_exhibitions, -> { where("? BETWEEN start_date AND end_date", Date.today) }
  scope :upcoming_exhibitions, -> { where("start_date > ?", Date.today) }
  scope :past_exhibitions, -> { where("end_date < ?", Date.today) }

  has_attached_file :exhibition_thumbnail, styles: { large: "1000x1000>", medium: "500x500>", square: "500x500>", small: "200x200>", thumb: "100x100>", tiny: "75x75>", }, convert_options: {square: " -gravity center -extent '500x500'", thumb: " -gravity center -extent '200x200'"}
  validates_attachment_content_type :exhibition_thumbnail, content_type: /\Aimage\/.*\z/

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |exhibition|
        csv << exhibition.attributes.values_at(*column_names)
      end
    end  
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      exhibition_hash = row.to_hash 
      exhibition = Exhibition.where(id: exhibition_hash["id"])

      if exhibition.count == 1
        exhibition.first.update_attributes(exhibition_hash)
      else
        Exhibition.create!(exhibition_hash)
      end # end if !winery.nil?
    end # end CSV.foreach
  end # end self.import(file)
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]
  

  # GET /exhibitions
  # GET /exhibitions.json
  def index
    # @current_exhibitions = Exhibition.where("? BETWEEN start_date AND end_date", Date.today).order('end_date ASC')
    @exhibitions = Exhibition.all
    @current_upcoming_exhibitions = Exhibition.where("end_date >= ?", Date.today).order('end_date ASC')
    @upcoming_exhibitions = Exhibition.where("start_date > ?", Date.today).order('end_date ASC')
    @ongoing_exhibitions = Exhibition.where("end_date > ?", Date.today + 4.months).order('end_date ASC')
    @past_exhibitions = Exhibition.where("end_date < ?", Date.today).order('end_date DESC')

    if params[:gallery_id]
      @exhibitions = Gallery.find(params[:gallery_id]).exhibitions
    elsif params[:current_exhibitions]
      @exhibitions = Exhibition.current_exhibitions.order('end_date ASC')
    elsif params[:upcoming_exhibitions]
      @exhibitions = Exhibition.upcoming_exhibitions
    elsif params[:past_exhibitions]
      @exhibitions = Exhibition.past_exhibitions.order('end_date DESC')
    else
      @exhibitions = Exhibition.where("? BETWEEN start_date AND end_date", Date.today).order('end_date ASC')
    end
    
    @exhibitions = Exhibition.all

    respond_to do |format|
      format.html
      format.csv { render text: @exhibitions.to_csv }

    end
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.json
  def show
  end

  # GET /exhibitions/new
  def new
    @exhibition = Exhibition.new(gallery_id: params[:gallery_id])
  end

  # GET /exhibitions/1/edit
  def edit
  end

  # POST /exhibitions
  # POST /exhibitions.json
  def create
    @exhibition = Exhibition.new(exhibition_params, params[:gallery_id])

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully created.' }
        format.json { render :show, status: :created, location: @exhibition }
      else
        format.html { render :new }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitions/1
  # PATCH/PUT /exhibitions/1.json
  def update
    respond_to do |format|
      if @exhibition.update(exhibition_params)
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibition }
      else
        format.html { render :edit }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1
  # DELETE /exhibitions/1.json
  def destroy
    @exhibition.destroy
    respond_to do |format|
      format.html { redirect_to exhibitions_url, notice: 'Exhibition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Exhibition.import(params[:file])
    redirect_to root_url, notice: "Exhibitions imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  
    def set_gallery
      @gallery = Gallery.find(params[:gallery_id])
    end

    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibition_params
      params.require(:exhibition).permit(:title, :start_date, :end_date, :description, :exhibition_thumbnail, :gallery_id)
    end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_exhibition.html.erb
<div id="exhibition-<%= exhibition.id %>">
  <div class="row">
    <div class="col-sm-5">
    <%= link_to image_tag(exhibition.exhibition_thumbnail.url(:small), class: "img-responsive", width: "100%"), exhibition %>
    </div>
    <div class="col-sm-7">
      <p><%= exhibition.start_date.try(:strftime, "%B %e") %> - 
      <%= exhibition.end_date.try(:strftime, "%B %e, %Y") %></p>
      <h3><%= link_to exhibition.title, exhibition %><br></h3>
      <p><%= exhibition.description %></p>
      <p><%= link_to 'About Exhibition', exhibition, class: "btn btn-primary" %>
    </div>
  </div>
  <hr>
</div>

app/views/exhibitions/_form.html.erb
<%= form_for([@exhibition]) do |f| %>
  <% if @exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibition.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
      <% @exhibition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_field :end_date, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :exhibition_thumbnail %><br />
    <%= f.file_field :exhibition_thumbnail %>
  </div>
  <div class="field">
    <%= f.label :gallery_id, "Gallery ID" %><br>
    <%= f.text_field :gallery_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exhibitions/edit.html.erb
<div class="container">
  <h1>Editing Exhibition</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @exhibition %> |
  <%= link_to 'Back', exhibitions_path %>
</div>

app/views/exhibitions/index.html.erb
<% content_for(:title, 'Exhibitions')%>
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<br>
<br>
<br>
<div class="container">
  <h2 class="page-title">Exhibitions</h2>
  <hr>
  <!-- Nav tabs -->
    <ul class="nav nav-pills gray" role="tablist">
      <li role="presentation" class="active"><a href="#current" aria-controls="home" role="tab" data-toggle="tab">Current & Upcoming</a></li>
      <li role="presentation"><a href="#ongoing" aria-controls="profile" role="tab" data-toggle="tab">Ongoing</a></li>
      <li role="presentation"><a href="#past" aria-controls="messages" role="tab" data-toggle="tab">Past</a></li>
    </ul>
  <br>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="current">
      <!-- Third Container (Grid) -->
      <div class="container bg-3">
        <div class="row">
          <% if @current_upcoming_exhibitions.any? %>
            <% @current_upcoming_exhibitions.each do |exhibition| %>
              <div class="col-sm-4 col-md-3">
                <div class="thumbnail thumbnail-exhibitions">
                  <%= link_to image_tag(exhibition.exhibition_thumbnail.url(:square), class: "img-responsive margin border"), exhibition %>
                  <div class="caption">
                    <div class="exhibitions-text1">
                      <p class="exhibitions-name"><%= link_to exhibition.title, exhibition %></p>
                    </div>
                    <div class="exhibitions-text2">
                      <p class="exhibitions-date">  
                      <% if exhibition.end_date > Date.today + 4.month %>
                        Ongoing
                      <% elsif exhibition.end_date > Date.today && exhibition.start_date < Date.today %>
                        Through <%= exhibition.end_date.try(:strftime, "%b %e, %Y") %>
                      <% elsif exhibition.end_date == exhibition.start_date %>
                        <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %>
                      <% elsif %>
                        <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %> - <%= exhibition.end_date.try(:strftime, "%b %e, %Y") %>
                      <% end %>
                        </p>

                      <p class="gallery-name"><%= link_to exhibition.gallery.try(:gallery_name), exhibition.gallery %></p>
                      <p class="gallery-address"><%= exhibition.gallery.try(:address) %><br>
                        <%= exhibition.gallery.try(:city) %>, <%= exhibition.gallery.try(:state) %> <%= exhibition.gallery.try(:zip) %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %> 
            <p>There are no current exhibitions at this time.</p>
          <% end %>
        </div>
      </div>
    </div><!-- end tab panel -->
    

    <div role="tabpanel" class="tab-pane" id="ongoing">
      <!-- Third Container (Grid) -->
      <div class="container bg-3">
        <div class="row">
          <% if @ongoing_exhibitions.any? %>
            <% @ongoing_exhibitions.each do |exhibition| %>
              <div class="col-sm-4 col-md-3">
                <div class="thumbnail thumbnail-exhibitions">
                  <%= link_to image_tag(exhibition.exhibition_thumbnail.url(:square), class: "img-responsive margin border"), exhibition %>
                  <div class="caption">
                    <div class="exhibitions-text1">
                      <p class="exhibitions-name"><%= link_to exhibition.title, exhibition %></p>
                    </div>
                    <div class="exhibitions-text2">
                      <p class="exhibitions-date">  
                      <% if exhibition.end_date > Date.today + 4.month %>
                        Ongoing
                      <% elsif exhibition.end_date > Date.today && exhibition.start_date < Date.today %>
                        Through <%= exhibition.end_date.try(:strftime, "%b %e, %Y") %>
                      <% elsif exhibition.end_date == exhibition.start_date %>
                        <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %>
                      <% elsif %>
                        <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %> - <%= exhibition.end_date.try(:strftime, "%b %e, %Y") %>
                      <% end %>
                        </p>

                      <p class="gallery-name"><%= link_to exhibition.gallery.try(:gallery_name), exhibition.gallery %></p>
                      <p class="gallery-address"><%= exhibition.gallery.try(:address) %><br>
                        <%= exhibition.gallery.try(:city) %>, <%= exhibition.gallery.try(:state) %> <%= exhibition.gallery.try(:zip) %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %> 
            <p>There are no ongoing exhibitions at this time.</p>
          <% end %>
        </div>
      </div>
    </div><!-- end tab panel -->

    <div role="tabpanel" class="tab-pane" id="past">
      <!-- Third Container (Grid) -->
      <div class="container bg-3">
        <div class="row">
          <% if @past_exhibitions.any? %>
            <% @past_exhibitions.each do |exhibition| %>
              <div class="col-sm-4 col-md-3">
                <div class="thumbnail thumbnail-exhibitions">
                  <%= link_to image_tag(exhibition.exhibition_thumbnail.url(:square), class: "img-responsive margin border"), exhibition %>
                  <div class="caption">
                    <div class="exhibitions-text1">
                      <p class="exhibitions-name"><%= link_to exhibition.title, exhibition %></p>
                    </div>
                    <div class="exhibitions-text2">
                      <p class="exhibitions-date">  
                      <% if exhibition.end_date > Date.today + 4.month %>
                        Ongoing
                      <% elsif exhibition.end_date > Date.today && exhibition.start_date < Date.today %>
                        Through <%= exhibition.end_date.try(:strftime, "%b %e, %Y") %>
                      <% elsif exhibition.end_date == exhibition.start_date %>
                        <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %>
                      <% elsif %>
                        <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %> - <%= exhibition.end_date.try(:strftime, "%b %e, %Y") %>
                      <% end %>
                        </p>

                      <p class="gallery-name"><%= link_to exhibition.gallery.try(:gallery_name), exhibition.gallery %></p>
                      <p class="gallery-address"><%= exhibition.gallery.try(:address) %><br>
                        <%= exhibition.gallery.try(:city) %>, <%= exhibition.gallery.try(:state) %> <%= exhibition.gallery.try(:zip) %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %> 
            <p>There are no past exhibitions at this time.</p>
          <% end %>
        </div>
      </div>
    </div><!-- end tab panel -->
  </div><!-- end tab content -->

<br>
<br>
<hr>
<br>
<p class="text-center">
    <% if admin_signed_in? %>
      <%= link_to 'Create New Exhibition', galleries_url, class: "btn btn-warning" %>
    <% end %>
  </p>
</div>

<p class="text-center">
  <% if admin_signed_in? %>
    <%= link_to 'Create New Exhibition', galleries_url, class: "btn btn-warning" %>
    <%= link_to 'New Gallery', new_gallery_path, class: "btn btn-warning" %>

    <h2>Import Exhibitions</h2>
  
    <%= form_tag import_exhibitions_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import CSV" %>
    <% end %>

    <p>
    Download: 
    <%= link_to "CSV", exhibitions_path(format: "csv") %> |
    <%= link_to "Excel", exhibitions_path(format: "xls") %>
    </p>

  <% end %>
</p>
<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>

app/views/exhibitions/new.html.erb
<div class="container">
  <h1>New Exhibition</h1>

  <%= render 'form' %>

  <%= link_to 'Back', galleries_path %>
</div>

app/views/exhibitions/show.html.erb
<div class="container">
  <hr>
  <div class="row">
      <div id="myCarousel-events" class="carousel slide" data-interval="false" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="myCarousel-events" data-slide-to="0" class="active"></li>
            <li data-target="myCarousel-events" data-slide-to="1"></li>
            <li data-target="myCarousel-events" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <%= image_tag(@exhibition.exhibition_thumbnail.url(:square), class: "img-responsive same-size-img") %>
            </div>
            <div class="item">
              <%= image_tag("design-project.jpg", class: "img-responsive same-size-img", style: "width:500px" ) %>
            </div>
            <div class="item">
             <%= image_tag("design-project.jpg", class: "img-responsive same-size-img", style: "width:500px" ) %>
            </div>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel-events" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel-events" role="button" data-slide="next">
            <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div><!-- End Carousel -->
    
    </div>


    <div class="row exhibition-heading">
      <h1><%= @exhibition.title %></h1>
      <p class="exhibition-date">
        <% if @exhibition.end_date > Date.today + 4.month %>
          Ongoing
        <% elsif @exhibition.end_date == @exhibition.start_date %>
          <%= @exhibition.start_date.try(:strftime, "%b %e, %Y") %>
        <% elsif %>
          <%= @exhibition.start_date.try(:strftime, "%B %e") %> - 
          <%= @exhibition.end_date.try(:strftime, "%B %e, %Y") %>
        <% end %>
      </p>
      <h4><%= link_to @exhibition.gallery.try(:gallery_name), gallery_path(@exhibition.gallery_id) %></h4>
        <p><%= @exhibition.gallery.try(:address) %><p>
        <div class="socials">
          <a href="https://www.facebook.com/chicagoartsdist" target="_blank"><i class="fa fa-facebook"></i></a>
          <a href="https://twitter.com/chicagoartsdist" target="_blank"><i class="fa fa-twitter"></i></a> 
          <a href="https://www.instagram.com/chicagoartsdistrict/" target="_blank"><i class="fa fa-instagram"></i></a>
        </div>
    </div>



<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p><%= markdown(@exhibition.description) %></p>
    </div>
    </div>
  </div>
</div>



  <br>
  <br>
  <p class="text-center">
    <% if admin_signed_in? %>
      <%= link_to 'Edit', edit_exhibition_path(@exhibition),class: "btn btn-warning" %>
    <% end %>
      <%= link_to 'All Exhibitions', exhibitions_path, class: "btn btn-primary" %>
    <% if admin_signed_in? %>
      <%= link_to 'Delete', @exhibition, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <% end %>
  </p>
  <br>
  <br>
</div>