config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :admins
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'about_2nd_fridays', to: 'pages#about_2nd_fridays'
  get 'funding', to: 'pages#funding'

  get 'pages/events'
  get 'pages/event_1'
  get 'pages/exhibitions'
  get 'pages/exhibition'
  get 'pages/calendar'
  get 'pages/calendar_all'

  get 'galleries/alumni_galleries'

  resources :galleries do
    collection { post :import}
  end 
  resources :exhibitions do
    collection { post :import}
  end
  resources :events do
    collection { post :import}
    member do
      post :participation
    end
  end
  resources :participations

  root 'pages#home'

end

app/views/shared/_footer.html.erb
  <div class="container">
    <footer class="footer">
      <p class="pull-left">© CHICAGO ARTS DISTRICT 2017. All Rights Reserved.</p>
      <div class="pull-right">

          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Sign Up for Newsletter
          </button>
          <br>

          <!-- Modal -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Sign Up for Newsletter</h4>
                </div><!-- end modal-header -->
                <div class="modal-body">
                    <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
            #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
            /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
               We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//chicagoartsdistrict.us16.list-manage.com/subscribe/post?u=47e3656cf9c905bbbbdbf5285&amp;id=87058cb3da" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
            <h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
            <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
            <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
            <label for="mce-FNAME">First Name </label>
            <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
            <label for="mce-LNAME">Last Name </label>
            <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group input-group">
    <strong>Interests </strong>
    <ul><li><input type="checkbox" value="1" name="group[1287][1]" id="mce-group[1287]-1287-0"><label for="mce-group[1287]-1287-0">2nd Fridays Gallery Night Newsletter</label></li>
<li><input type="checkbox" value="2" name="group[1287][2]" id="mce-group[1287]-1287-1"><label for="mce-group[1287]-1287-1">East Pilsen Info &amp; Updates</label></li>
<li><input type="checkbox" value="4" name="group[1287][4]" id="mce-group[1287]-1287-2"><label for="mce-group[1287]-1287-2">Leasing Information: Commercial</label></li>
<li><input type="checkbox" value="8" name="group[1287][8]" id="mce-group[1287]-1287-3"><label for="mce-group[1287]-1287-3">Leasing Information: Residential</label></li>
</ul>
</div>
            <div id="mce-responses" class="clear">
                        <div class="response" id="mce-error-response" style="display:none"></div>
                        <div class="response" id="mce-success-response" style="display:none"></div>
            </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_47e3656cf9c905bbbbdbf5285_87058cb3da" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
 
                </div><!-- end modal-body -->
              </div><!-- end modal-content -->
            </div><!-- end modal-dialog -->
          </div><!-- end modal fade -->
      </div><!-- end pull-right -->
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("LOGO.jpg", height: "100", class: "red_border"), root_path %>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ABOUT <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= 'active' if current_page?(events_path) %>"><%= link_to "ABOUT THE CHICAGO ARTS DISTRICT", about_path %></li>
            <li class="<%= 'active' if current_page?(exhibitions_path) %>"><%= link_to "FUNDING FOR THE CHICAGO ARTS DISTRICT", funding_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">EVENTS & EXHIBITIONS <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= 'active' if current_page?(events_path) %>"><%= link_to "EVENTS", events_path %></li>
            <li class="<%= 'active' if current_page?(exhibitions_path) %>"><%= link_to "EXHIBITIONS", exhibitions_path %></li>
            <li class="<%= 'active' if current_page?(about_2nd_fridays_path) %>"><%= link_to "2nd FRIDAYS", about_2nd_fridays_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">GALLERIES<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= 'active' if current_page?(galleries_path) %>"><%= link_to "GALLERIES", galleries_path %></li>
            <li class="<%= 'active' if current_page?(galleries_alumni_galleries_path) %>"><%= link_to "ALUMNI GALLERIES", galleries_alumni_galleries_path %></li>
          </ul>
        </li>
        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "CONTACT", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if admin_signed_in? %>
        <li><%= link_to "sign out", destroy_admin_session_path, method: :delete %></li>
      <% end %>
        <!-- Button trigger modal -->
            <li><div class="btn-nav"><a class="btn btn-primary btn-small navbar-btn" data-toggle="modal" data-target="#myModal">Sign Up for Newsletter</a></div></li>
              
          <!-- Modal -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Sign Up for Newsletter</h4>
                </div><!-- end modal-header -->
                <div class="modal-body">
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
            #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
            /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
               We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//chicagoartsdistrict.us16.list-manage.com/subscribe/post?u=47e3656cf9c905bbbbdbf5285&amp;id=87058cb3da" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
           
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
            <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
            <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
            <label for="mce-FNAME">First Name </label>
            <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
            <label for="mce-LNAME">Last Name </label>
            <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group input-group">
    <strong>Interests </strong>
    <ul><li><input type="checkbox" value="1" name="group[1287][1]" id="mce-group[1287]-1287-0"><label for="mce-group[1287]-1287-0">2nd Fridays Gallery Night Newsletter</label></li>
<li><input type="checkbox" value="2" name="group[1287][2]" id="mce-group[1287]-1287-1"><label for="mce-group[1287]-1287-1">East Pilsen Info &amp; Updates</label></li>
<li><input type="checkbox" value="4" name="group[1287][4]" id="mce-group[1287]-1287-2"><label for="mce-group[1287]-1287-2">Leasing Information: Commercial</label></li>
<li><input type="checkbox" value="8" name="group[1287][8]" id="mce-group[1287]-1287-3"><label for="mce-group[1287]-1287-3">Leasing Information: Residential</label></li>
</ul>
</div>
            <div id="mce-responses" class="clear">
                        <div class="response" id="mce-error-response" style="display:none"></div>
                        <div class="response" id="mce-success-response" style="display:none"></div>
            </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_47e3656cf9c905bbbbdbf5285_87058cb3da" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
 
                </div><!-- end modal-body -->
              </div><!-- end modal-content -->
            </div><!-- end modal-dialog -->
          </div><!-- end modal fade -->
      </ul>
    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>