config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :admins
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'about_2nd_fridays', to: 'pages#about_2nd_fridays'
  get 'funding', to: 'pages#funding'

  get 'pages/events'
  get 'pages/event_1'
  get 'pages/exhibitions'
  get 'pages/exhibition'
  get 'pages/calendar'
  get 'pages/calendar_all'

  get 'galleries/alumni_galleries'

  resources :galleries do
    collection { post :import}
  end 
  resources :exhibitions do
    collection { post :import}
  end
  resources :events do
    collection { post :import}
    member do
      post :participation
    end
  end
  resources :participations

  root 'pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_many :participations
  has_many :galleries, :through => :participations
  accepts_nested_attributes_for :galleries


  scope :upcoming, -> { where("start_date >= ?", Date.today) }
  scope :past, -> { where("end_date < ?", Date.today) }

  
  require 'csv'

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |event|
        csv << event.attributes.values_at(*column_names)
      end
    end  
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      event_hash = row.to_hash 

      event = Event.where(id: event_hash["id"])

      if event.count == 1
        event.first.update_attributes(event_hash)
      else
        Event.create!(event_hash)
      end # end if !event.nil?
    end # end CSV.foreach
  end # end self.import(file)
              

   has_attached_file :event_thumbnail, styles: { large: "1000x1000#", medium: "500x500#", small: "200x200#", thumb: "100x100#", tiny: "75x75#", }
  validates_attachment_content_type :event_thumbnail, content_type: /\Aimage\/.*\z/
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :add_gallery, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /events
  # GET /events.json

  def index
    @current_and_upcoming_events = Event.where.not(event_type: 'Participation').where("start_date >= ?", Date.today).order('end_date ASC').order('end_date ASC')
    @past_events = Event.where.not(event_type: 'Participation').where("end_date < ?", Date.today).order('end_date DESC')

    if params[:upcoming]
      @events = Event.upcoming.order('start_date ASC, title ASC')
    elsif params[:past]
      @events = Event.past.order('start_date DESC, title ASC')
    else
      @events = Event.where("start_date >= ?", Date.today).order('start_date ASC, title ASC')
    end

    respond_to do |format|
      format.html
      format.csv { render text: @past_events.to_csv }

    end

  end

  # GET /events/1
  # GET /events/1.json
  def show 
    @galleries = @event.galleries
    @exhibitions = Exhibition.all

    if params[:exhibition_id]
      @events = Exhibition.find(params[:exhibition_id]).events
    else
      @events = Event.find(params[:id])
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params, params[:gallery_id])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Exhibition was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /events/1/participation
  def participation
    @event = Event.find(params[:id])
    @gallery = Gallery.find(params[:id])
    @gallery.events << @event
    redirect_to @event
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Event.import(params[:file])
    redirect_to root_url, notice: "Events imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibition
      @exhibtion = Exhibition.find(params[:exhibition_id])
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :start_time, :end_time, :description, :event_thumbnail, :event_type)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for([@event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_field :end_date, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_field :start_time, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_field :end_time, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :event_thumbnail %><br />
    <%= f.file_field :event_thumbnail %>
  </div>
   <div class="field">
    <%= f.label :event_type %><br>
    <%= f.select :event_type, ['Series', 'Single', 'Participation'] %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container"> 
  <h1>Editing Event</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @event %> |
  <%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<% content_for(:title, 'Events')%>
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<br>
<br>
<br>
<div class="container">
  <h2 class="page-title">Events</h2>
  <hr>
  <!-- Nav tabs -->
  <ul class="nav nav-pills gray" role="tablist">
    <li role="presentation" class="active"><a href="#current_upcoming" aria-controls="home" role="tab" data-toggle="tab">Current & Upcoming</a></li>
    <li role="presentation"><a href="#past" aria-controls="messages" role="tab" data-toggle="tab">Past</a></li>
  </ul>
  <br>

  <!-- Tab panes -->
  <div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="current_upcoming">
      <% @current_and_upcoming_events.each do |event| %>
      <% if event.event_type == "Series" %>
        <div class="container-fluid gray-background">
          <div class="row">
            <div class="col-md-3">
              <%= link_to image_tag(event.event_thumbnail.url(:medium), class: "img-responsive img-border"), event %>
            </div>
            <div class="col-md-9 events-index-info">
              <div class="row events-text1">
                <p class="date"><%= event.start_date.try(:strftime, "%A, %B %e, %Y") %></p>
                <h2><%= link_to "#{event.title} - #{event.start_date.try(:strftime, "%B" )}", event %></h2>
                <br>
                <p><%= event.start_time.try(:strftime, "%l:%M %p") %> - <%= event.end_time.try(:strftime, "%l:%M %p") %></p>
              </div>
              <div class="row events-text2">
                <br>
                <br>
                <br>
                <br>
                 <p class="gallery-name"><strong><%= link_to 'Information Center', about_2nd_fridays_path %></strong></p>
                  <p class="gallery-address">1945 S. Halsted St.<br>
                  Chicago, IL 60608</p>
              </div>
            </div>
          </div>
          <br>
          <div class="row">  
            <div class="col-md-3">
              <h4 class="align-right">Participating<br>Galleries</h4>
            </div>
            <div class="col-md-9">
              <% if event.galleries.any? %>
              <hr>
              <% event.galleries.each do |gallery| %>
                    <div class="col-md-2">
                      <div class="image-container">
                        <%= image_tag(gallery.thumbnail.url(:medium), class: "img-responsive same-size-img") %>
                        <div class="overlay">
                          <h6 class="text-overlay"><%= link_to gallery.gallery_name, gallery %></h6>
                        </div>
                      </div>
                    </div>
              <% end %>
              <% else %>
               <p>Participating Galleries will be announced soon!<br>
                Sign up for updates!</p>
                <div class="newsletter-signup-form"><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Sign Up for Newsletter</button>
                  </div> 
                  <br>
            <% end %>
            </div>
          </div><!-- end row -->
        </div>

        <% else %>
          <div class="row events-information">
            <div class="col-md-2 ">
              <%= link_to image_tag(event.event_thumbnail.url(:medium), class: "img-responsive margin border"), event %>
            </div>
            <div class="col-md-10">
              <p><%= event.start_date.try(:strftime, "%A, %B %e, %Y") %></p>
              <p><%= event.start_time.try(:strftime, "%l:%M %p") %> - <%= event.end_time.try(:strftime, "%l:%M %p") %></p> 
              <h3><%= link_to event.title, event %></h3>
              <br>
              <% if event.event_type != "Series" %>
                <% event.galleries.each do |gallery| %>
                  <h5><%= link_to gallery.gallery_name, gallery %><br>
                  <%= gallery.address %></h5>
                <% end %>
              <% end %>
            </div>
          </div><!-- end row -->
        <% end %>
        <hr>
      <% end %>


  </div><!-- end tab panel -->

    <div role="tabpanel" class="tab-pane" id="past">
      <% @past_events.each do |event| %>
        <% if event.event_type == "Series" %>
        <div class="container-fluid gray-background">
          <div class="row">
            <div class="col-md-3">
              <%= link_to image_tag(event.event_thumbnail.url(:medium), class: "img-responsive img-border"), event %>
            </div>
            <div class="col-md-9 events-index-info">
              <div class="row events-text1">
                <p class="date"><%= event.start_date.try(:strftime, "%A, %B %e, %Y") %></p>
                <h2><%= link_to "#{event.title} - #{event.start_date.try(:strftime, "%B" )}", event %></h2>
                <br>
                <p><%= event.start_time.try(:strftime, "%l:%M %p") %> - <%= event.end_time.try(:strftime, "%l:%M %p") %></p>
              </div>
              <div class="row events-text2">
                <br>
                <br>
                <br>
                <br>
                 <p class="gallery-name"><strong><%= link_to 'Information Center', about_2nd_fridays_path %></strong></p>
                  <p class="gallery-address">1945 S. Halsted St.<br>
                  Chicago, IL 60608</p>
              </div>
            </div>
          </div>
          <br>
          <div class="row">  
            <div class="col-md-3">
              <h4 class="align-right">Participating<br>Galleries</h4>
            </div>
            <div class="col-md-9">
              <% if event.galleries.any? %>
              <hr>
              <% event.galleries.each do |gallery| %>
                    <div class="col-md-2">
                      <div class="image-container">
                        <%= image_tag(gallery.thumbnail.url(:medium), class: "img-responsive same-size-img") %>
                        <div class="overlay">
                          <h6 class="text-overlay"><%= link_to gallery.gallery_name, gallery %></h6>
                        </div>
                      </div>
                    </div>
              <% end %>
              <% else %>
               <p>Participating Galleries will be announced soon!<br>
                Sign up for updates!</p>
                <div class="newsletter-signup-form"><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Sign Up for Newsletter</button>
                  </div> 
                  <br>
            <% end %>
            </div>
          </div><!-- end row -->
        </div>
        <% else %>
          <div class="row events-information">
            <div class="col-md-2 ">
            <% if event.event_thumbnail.present? %>
              <%= link_to image_tag(event.event_thumbnail.url(:medium), class: "img-responsive margin border"), event %>
            <% end %>
            </div>
            <div class="col-md-10">
              <span class="events-date"><%= event.start_date.try(:strftime, "%A, %B %e, %Y") %></span>
              <p class="events-time"><%= event.start_time.try(:strftime, "%l:%M %p") %> - <%= event.end_time.try(:strftime, "%l:%M %p") %></p> 
              <h3 class="event-name"><%= link_to event.title, event %></h3>
              <br>
              <% if event.event_type != "Series" %>
                <% event.galleries.each do |gallery| %>
                  <h5><%= link_to gallery.gallery_name, gallery %><br>
                  <%= gallery.address %></h5>
                <% end %>
              <% end %>
            </div>
          </div><!-- end row -->
        <% end %>
        <hr>
      <% end %>
      </div>
    </div><!-- end tab panel -->
  </div><!-- end tab content -->
  <p class="text-center">
  <% if admin_signed_in? %>
  <%= link_to 'Create New Event', new_event_path, class: "btn btn-warning" %>

  <h2>Import Events</h2>
  
    <%= form_tag import_events_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import CSV" %>
    <% end %>

    <p>
    Download: 
    <%= link_to "CSV", events_path(format: "csv") %> |
    <%= link_to "Excel", events_path(format: "xls") %>
    </p>

  <% end %>
</p>

</div>


<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>

app/views/events/new.html.erb
<div class="container">
  <h1>New Event</h1>

  <%= render 'form' %>
<br>
  <%= link_to 'Back', exhibitions_path, class: "btn btn-default" %>
</div>

app/views/events/show.html.erb
<div class="container">
  <hr>
  <div class="row">
    <div class="col-md-6 col-xs-6-push">
      <div id="myCarousel-events" class="carousel slide" data-interval="false" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="myCarousel-events" data-slide-to="0" class="active"></li>
          <li data-target="myCarousel-events" data-slide-to="1"></li>
          <li data-target="myCarousel-events" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <% if @event.event_thumbnail.present? %>
              <%= image_tag(@event.event_thumbnail.url(:medium), class: "img-responsive same-size-img") %>
            <% end %>
          </div>
          <div class="item">
            <%= image_tag(@event.event_thumbnail.url(:medium), class: "img-responsive same-size-img") %>
          </div>
          <div class="item">
           <%= image_tag(@event.event_thumbnail.url(:medium), class: "img-responsive same-size-img") %>
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel-events" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel-events" role="button" data-slide="next">
          <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div><!-- End Carousel -->

    </div><!-- End col -->
  
    <div class="col-md-6 col-xs-6-pull event-show-info">
      <p class="page-title">EVENT</p><br>
      <h2><%= @event.title %></h2>
      <p class="date-info"><%= @event.start_date.try(:strftime, "%A, %B %e, %Y") %><br>
      <%= @event.start_time.try(:strftime, "%l:%M %p") %> - <%= @event.end_time.try(:strftime, "%l:%M %p") %></p>
      <br>
      <br>
    <% if @event.event_type != "Series" %>
       <% @galleries.each do |gallery| %>
          <h4><%= link_to gallery.gallery_name, gallery %><br>
            <%= gallery.address %></h4>
      <% end %>
    <% end %>
    <br>
      <h4>Event Description</h4>
      <p><%= markdown(@event.description) %></p>
      <br>
    </div>

  </div><!-- End Row -->

</div><!-- End Container -->

<!-- Third Container (Grid) -->
<div class = "container">
  <div class="row">
    <% if @event.event_type == "Series" %>
      <h3 class="page-title">This Month's Participating Galleries</h3>
      <hr>
      <% if @event.galleries.any? %>  
        <% @galleries.each do |gallery| %>
          <div class="col-xs-4 col-sm-2">
            <div class="image-container">
              <%= image_tag(gallery.thumbnail.url(:medium), class: "img-responsive same-size-img events-border") %>
              <div class="overlay">
                <h6 class="text-overlay"><%= link_to gallery.gallery_name, gallery %></h6>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h4>Participating Galleries will be announced soon! Sign up for updates!</h4>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Sign Up for Newsletter</button>
<% end %>
    <% end %>
  </div>
</div>
  
  <br>


<!-- Third Container (Grid) -->
<div class = "container">
    <% if @event.event_type == "Series" %>
      <h3 class="page-title">This Month's Participating Galleries</h3>
      <hr>
      <% if @event.galleries.any? %>  
        <% @galleries.each do |gallery| %>
          <%= link_to gallery.gallery_name, gallery %>
          <%= image_tag(gallery.thumbnail.url(:thumb), class: "img-responsive same-size-img events-border") %>
          <% if gallery.exhibitions.any? %>
            <% gallery.exhibitions.each do |exhibition| %>
              <%= exhibition.title %><br>
            <% end %>
          <% else %>
            no
          <% end %>
          <hr>
        <% end %>
      <% end %>
    <% end %>

</div>




      <br>
    <p class="text-center">
      <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_event_path,class: "btn btn-warning" %>
      <% end %>
        <%= link_to 'All Events', events_path, class: "btn btn-primary"  %>
      <% if admin_signed_in? %>
        <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
    </p>
    <br>
    <br>
</div>