config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :admins
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'about_2nd_fridays', to: 'pages#about_2nd_fridays'
  get 'funding', to: 'pages#funding'

  get 'pages/events'
  get 'pages/event_1'
  get 'pages/exhibitions'
  get 'pages/exhibition'
  get 'pages/calendar'
  get 'pages/calendar_all'

  get 'galleries/alumni_galleries'

  resources :galleries do
    collection { post :import}
  end 
  resources :exhibitions do
    collection { post :import}
  end
  resources :events do
    collection { post :import}
    member do
      post :participation
    end
  end
  resources :participations

  root 'pages#home'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :exhibitions, dependent: :destroy
  accepts_nested_attributes_for :exhibitions
 
  has_many :participations
  has_many :events, :through => :participations
  accepts_nested_attributes_for :events
  
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  require 'csv'

  def self.to_csv (options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |gallery|
        csv << gallery.attributes.values_at(*column_names)
      end
    end  
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      gallery_hash = row.to_hash 

      gallery = Gallery.where(id: gallery_hash["id"])

      if gallery.count == 1
        gallery.first.update_attributes(gallery_hash)
      else
        Gallery.create!(gallery_hash)
      end # end if !winery.nil?
    end # end CSV.foreach
  end # end self.import(file)

  has_attached_file :thumbnail, styles: { large: "1000x1000#", medium: "600x600#", small: "200x200#", thumb: "100x100#", tiny: "75x75#", }
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
  
end


    

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show, :alumni_galleries]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.where(current: true).order('gallery_name ASC')
    @alumni_galleries = Gallery.where(current: true).order('gallery_name ASC')
    
    respond_to do |format|
      format.html
      format.csv { render text: @galleries.to_csv }

    end
  end


  def alumni_galleries
    @alumni_galleries = Gallery.where(current: false).order('gallery_name ASC')

    respond_to do |format|
      format.html
      format.csv { render text: @alumni_galleries.to_csv }

    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show

    @upcoming_exhibitions = @gallery.exhibitions.where("end_date >=?", Date.today).order('start_date ASC')
    @past_exhibitions = @gallery.exhibitions.where("exhibitions.end_date < ?", Date.today).order('end_date DESC')

    if params[:upcoming_gallery_exhibitions]
      @exhibitions = @gallery.exhibitions.where("end_date >=?", Date.today).order('end_date ASC')
    elsif params[:past_gallery_exhibitions]
      @exhibitions = @gallery.exhibitions.where("exhibitions.end_date < ?", Date.today)
    else
      @exhibitions = @gallery.exhibitions.where("end_date>=?", Date.today).order('end_date 
        ASC')
    end
    @events = Event.all.where("start_date>=?", Date.today).order('start_date ASC')

    @participations = @gallery.participations
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Gallery.import(params[:file])
    redirect_to root_url, notice: "Galleries imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:gallery_name, :address, :city, :state, :zip, :latitude, :longitude, :phone, :website, :email, :owner_operator, :medium, :description, :thumbnail, :hours, :current,
        :exhibitions_attributes => [:id, :title, :date, :description], 
        :events_attributes => [:id, :title, :date, :description],
        :participations_attributes => [:id] )
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end
end

app/views/galleries/_form.html.erb
<div class="row">
  <%= form_for @gallery, html: { class: 'form-horizontal' } do |f| %>
    <% if @gallery.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

        <ul>
        <% @gallery.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="control-group">
      <%= f.label :gallery_name, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :gallery_name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :address %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :city, class: 'control-label'%><br>
      <div class="controls">
        <%= f.text_field :city %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :state, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :state %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :zip, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :zip %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :phone, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :phone %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :website, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :website %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :email %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :owner_operator, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :owner_operator %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :medium, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :medium %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :description %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :hours, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :hours %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :thumbnail, class: 'control-label' %><br />
      <div class="controls">
        <%= f.file_field :thumbnail  %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :current, class: 'control-label' %><br />
      <div class="controls">
        <%= f.check_box :current  %>
      </div>
    </div>

    <br>

    <div class="control-group">
      <div class="controls">
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>


  </div>
  <br>
</div>

app/views/galleries/_gallery.html.erb
<li>
  <%= gallery.gallery_name %>
            <%= link_to image_tag(gallery.thumbnail.url(:thumb)), gallery %>
            <div class="caption gallery-text">
              <h5 class="gallery-name"><%= link_to gallery.gallery_name, gallery %></h5>
              <p class="gallery-address">
                <%= gallery.address %><br>
                <%= gallery.city %>, <%= gallery.state %> <%= gallery.zip %>
              </p>
              <hr>
              <p class="gallery-medium"><%= gallery.medium %></p>
</li>

app/views/galleries/alumni_galleries.erb
<% content_for(:title, 'Galleries')%>
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<br>
<br>
<br>

<div class="container">
  <h2 class="page-title">Galleries</h2>
  <hr>
  <br>
  <div class="row">
      <% @alumni_galleries.each do |gallery| %>
        <div class="col-md-3 col-sm-4">
          <div class="thumbnail thumbnail-galleries">
            <%= link_to image_tag(gallery.thumbnail.url(:medium), class: "img-responsive aspect"), gallery %>
            <div class="caption gallery-text">
              <h5 class="gallery-name"><%= link_to gallery.gallery_name, gallery %></h5>
              <p class="gallery-address">
                <%= gallery.address %><br>
                <%= gallery.city %>, <%= gallery.state %> <%= gallery.zip %>
              </p>
              <hr>
              <p class="gallery-medium"><%= gallery.medium %></p>
            </div>
          </div> 
          <br>   
        </div>

      <% end %>
      <br>
  </div>
<br>
<br>

<div class="row">
  <p class="text-center">
    <%= link_to 'Back to Galleries', galleries_path, class: "btn btn-primary" %>
  </p>
</div>

<hr>

<p class="text-center">
  <% if admin_signed_in? %>
    <%= link_to 'New Gallery', new_gallery_path, class: "btn btn-warning" %>

    <h2>Import Galleries</h2>
  
    <%= form_tag import_galleries_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import CSV" %>
    <% end %>

    <p>
    Download: 
    <%= link_to "CSV", galleries_path(format: "csv") %> |
    <%= link_to "Excel", galleries_path(format: "xls") %>
    </p>
    
  <% end %>
</p>





<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <div class="map_container">
      <div id="map_canvas" class="map_canvas"></div>
    </div>
  </div>
</div>
  <script type="text/javascript">
    handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map_canvas'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });

      // adds the users current location based on browser GPS
        function addCurrentLocation() {

          function displayOnMap(position){
            var marker = handler.addMarker({
              lat: position.coords.latitude,
              lng: position.coords.longitude,
              picture: {
                url: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png",
                width:  36,
                height: 36
              },
              infowindow: "This is you!"
            });
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            // handler.map.centerOn(marker);
          };

          if(navigator && navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(displayOnMap);  
          }

        }

        addCurrentLocation();
  </script>


</div><!-- end container -->


<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>


<script type="text/javascript">
$(document).ready(function(){
$screensize = $(window).width();
    if ($screensize > 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(3n)').after('<span class="clearfix visible-lg-block"></span>');
    }
    if ($screensize < 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(3n)').after('<span class="clearfix visible-lg-block visible-md-block"></span>');
    }
    if ($screensize < 991) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(3n)').after('<span class="clearfix visible-lg-block visible-sm-block"></span>');
    }
$( window ).resize(function() {
    $screensize = $(window).width();
    if ($screensize > 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(2n)').after('<span class="clearfix visible-lg-block"></span>');
    } 
    if ($screensize < 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(2n)').after('<span class="clearfix visible-lg-block visible-md-block"></span>');
    }
    if ($screensize < 991) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(2n)').after('<span class="clearfix visible-lg-block visible-sm-block"></span>');
    }
    if ($screensize < 767) {
        $(".item-layout > .clearfix").remove();
    }
});
});
</script>

app/views/galleries/edit.html.erb
<div class="container">
  <h1>Editing Gallery</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @gallery %> |
  <%= link_to 'Back', galleries_path %>
</div>

app/views/galleries/index.html.erb
<% content_for(:title, 'Galleries')%>
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<br>
<br>
<br>

<div class="container">
  <h2 class="page-title">Galleries</h2>
  <hr>
  <br>
  <div class="row">
      <% @galleries.each do |gallery| %>
        <div class="col-md-3 col-sm-4">
          <div class="thumbnail thumbnail-galleries">
            <%= link_to image_tag(gallery.thumbnail.url(:medium), class: "img-responsive aspect"), gallery %>
            <div class="caption gallery-text">
              <h5 class="gallery-name"><%= link_to gallery.gallery_name, gallery %></h5>
              <p class="gallery-address">
                <%= gallery.address %><br>
                <%= gallery.city %>, <%= gallery.state %> <%= gallery.zip %>
              </p>
              <hr>
              <p class="gallery-medium"><%= gallery.medium %></p>
            </div>
          </div> 
          <br>   
        </div>

      <% end %>
      <br>
      
  </div>
  <br>
  <br>
  <div class="row">
    <p class="text-center">
      <%= link_to 'Alumni Galleries', galleries_alumni_galleries_path, class: "btn btn-primary" %>
    </p>
  </div>

<br>
<br>

<hr>

<p class="text-center">
  <% if admin_signed_in? %>
    <%= link_to 'New Gallery', new_gallery_path, class: "btn btn-warning" %>

    <h2>Import Galleries</h2>
  
    <%= form_tag import_galleries_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import CSV" %>
    <% end %>

    <p>
    Download: 
    <%= link_to "CSV", galleries_path(format: "csv") %> |
    <%= link_to "Excel", galleries_path(format: "xls") %>
    </p>

  <% end %>
</p>


<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <div class="map_container">
      <div id="map_canvas" class="map_canvas"></div>
    </div>
  </div>
</div>
  <script type="text/javascript">
    handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map_canvas'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });

      // adds the users current location based on browser GPS
        function addCurrentLocation() {

          function displayOnMap(position){
            var marker = handler.addMarker({
              lat: position.coords.latitude,
              lng: position.coords.longitude,
              picture: {
                url: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png",
                width:  36,
                height: 36
              },
              infowindow: "This is you!"
            });
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            // handler.map.centerOn(marker);
          };

          if(navigator && navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(displayOnMap);  
          }

        }

        addCurrentLocation();
  </script>


</div><!-- end container -->


<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>


<script type="text/javascript">
$(document).ready(function(){
$screensize = $(window).width();
    if ($screensize > 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(3n)').after('<span class="clearfix visible-lg-block"></span>');
    }
    if ($screensize < 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(3n)').after('<span class="clearfix visible-lg-block visible-md-block"></span>');
    }
    if ($screensize < 991) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(3n)').after('<span class="clearfix visible-lg-block visible-sm-block"></span>');
    }
$( window ).resize(function() {
    $screensize = $(window).width();
    if ($screensize > 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(2n)').after('<span class="clearfix visible-lg-block"></span>');
    } 
    if ($screensize < 1199) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(2n)').after('<span class="clearfix visible-lg-block visible-md-block"></span>');
    }
    if ($screensize < 991) {
        $(".item-layout > .clearfix").remove();
        $('.item-layout .item:nth-child(2n)').after('<span class="clearfix visible-lg-block visible-sm-block"></span>');
    }
    if ($screensize < 767) {
        $(".item-layout > .clearfix").remove();
    }
});
});
</script>

app/views/galleries/new.html.erb
<div class="container">
  <h1>New Gallery</h1>

  <%= render 'form' %>
<br>
  <%= link_to 'Back', galleries_path, class: "btn btn-default"  %>
</div>

app/views/galleries/show.html.erb
<div class="container">
    <hr>
  <div class="row">
    <div class="col-md-5 col-md-offset-6">
      <p class="page-title">Gallery</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 col-md-offset-1">
      <%= image_tag(@gallery.thumbnail.url(:medium), class: "img-responsive") %>
    </div>
    <div class="col-md-5">
      
      <h1><%= @gallery.gallery_name %></h1>
        <p class="lead-text"><em><%= @gallery.medium %></em></p><br>
      <% if @gallery.current == true %>
        <h4><%= @gallery.address %><br>
        <%= @gallery.city %>, <%= @gallery.state %> <%= @gallery.zip %><br>
        <%= @gallery.phone %><br>
        <%= link_to @gallery.website, "http://#{@gallery.website}" %></h4>
        <br>
        <br>
        <h5><strong>Owner/Operator:</strong></h5>

        <%= @gallery.owner_operator %>
        <br>
        <h5><strong>Hours:</strong></h5>

          <%= markdown(@gallery.hours) %>
      <% else %>
        <h3>Gallery Alumni </h3>
      <% end %>
        
  
    </div>
  </div><!-- end row-->
  <br>
  <br>
  <div class="row">
    <div class="col-md-10 col-md-offset-1"> 
      <h2>About</h2>
      <p><%= markdown(@gallery.description) %></p>
      <br>
      <br>
      <p>
      <%= link_to "Visit Website", url_with_protocol(@gallery.website), class: "btn btn-success btn-sm sharp", :target => '_blank' %>
        <%= link_to "Email Gallery", url_with_protocol(@gallery.website), class: "btn btn-success btn-sm sharp", :target => '_blank' %>
      </p>
    </div>
  </div>
</div>
<br>
<br>
<div class="container gray-background">
  <h2>Exhibitions</h2>

      <!-- Nav tabs -->
      <ul class="nav nav-pills gray" role="tablist">
        <li role="presentation" class="active"><a href="#current" aria-controls="home" role="tab" data-toggle="tab">Current & Upcoming</a></li>
        <li role="presentation"><a href="#past" aria-controls="profile" role="tab" data-toggle="tab">Past</a></li>

      </ul>

    <!-- Tab panes -->
    <div class="tab-content">

      <div role="tabpanel" class="tab-pane active" id="current">
      <% if @upcoming_exhibitions.any? %>
        <% @upcoming_exhibitions.each do |exhibition| %>
        <hr>
          <div class="row">
            <div class="col-md-4 col-md-offset-1">
              <%= image_tag(exhibition.exhibition_thumbnail.url(:square), class: "img-responsive", width: "100%") %>
            </div>
            <div class="col-md-6">
              <p class="date">
                <% if exhibition.end_date > Date.today + 4.month %>
                  Ongoing
                <% elsif exhibition.end_date == exhibition.start_date %>
                  <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %>
                <% elsif %>
                  <%= exhibition.start_date.try(:strftime, "%B %e") %> - <%= exhibition.end_date.try(:strftime, "%B %e, %Y") %>
                <% end %>
              </p>
              <h3><%= link_to exhibition.title, exhibition %><br></h3>
              <p><%= truncate(markdown(exhibition.description), length: 675, escape: false )%></p>
              <p><%= link_to 'More About Exhibition', exhibition, class: "btn btn-primary" %>
            </div>
          </div><!-- end row -->
      
        <% end %>
      <% else %> 
        <div class="row">
          <div class="col-md-8">
            <br>
            <br>
            <h4>There are no upcoming exhibitions scheduled at this time.</h4>
            <br>
            <br>
          </div>
        </div><!-- end row -->
      <% end %>
    </div><!-- end tabpanel -->

    <div role="tabpanel" class="tab-pane" id="past">
      <% if @past_exhibitions.any? %>
        <% @past_exhibitions.each do |exhibition| %>
          <hr>
          <div class="row">
            <div class="col-md-5">
              <%= image_tag(exhibition.exhibition_thumbnail.url(:square), class: "img-responsive", width: "100%") %>
            </div>
            <div class="col-md-7">
              <p>
                <% if exhibition.end_date > Date.today + 4.month %>
                  Ongoing
                <% elsif exhibition.end_date == exhibition.start_date %>
                  <%= exhibition.start_date.try(:strftime, "%b %e, %Y") %>
                <% elsif %>
                  <%= exhibition.start_date.try(:strftime, "%B %e") %> - <%= exhibition.end_date.try(:strftime, "%B %e, %Y") %>
                <% end %>
              </p>
              <h3><%= link_to exhibition.title, exhibition %><br></h3>
              <p><%= truncate(markdown(exhibition.description), length: 675, escape: false )%></p>
              <p><%= link_to 'More About Exhibition', exhibition, class: "btn btn-primary" %>
            </div>
          </div><!-- end row -->
        
        <% end %>
      <% else %>
        <div class="row">
          <div class="col-md-8">
            <br>
            <br>
            <h4>There have been no past exhibitions.</h4>
            <br>
            <br>
          </div>
        </div><!-- end row -->
      <% end %>
    </div><!-- end tabpanel -->

  </div><!-- end tab-content -->
    <p>
      <% if admin_signed_in? %>
        <br>
        <br>
        <%= link_to "Add New Exhibition", new_exhibition_path(gallery_id: @gallery), class: "btn btn-warning" %>
        <br>
        <br>
      <% end %>
    </p>
</div><!-- end container -->
  
<br>
<br>
<div class="container">

    <% if admin_signed_in? %>
    <p>Sign up for upcoming 2nd Fridays</p>
      <% for event in @events %>
     <p><strong><%= event.title %></strong><br>
      <%= event.start_date.try(:strftime, "%A, %B %e, %Y") %><br>
        <%= link_to 'Sign up', new_participation_path(gallery_id: @gallery, event_id: event) %>
      <% end %>
     </p> 
    <% end %>

    
    <% @participations.each do |participation| %>
      <p>
        <%= link_to participation.event.title, participation %><br>
        <%= participation.event.start_date.try(:strftime, "%B, %e, %Y") %><br>
        <%= participation.description %><br>
        <%= link_to 'Edit', edit_participation_path(@gallery) %>
      </p>
    <% end %>

</div>

<p class="text-center">
  <% if admin_signed_in? %>
    <%= link_to 'Edit', edit_gallery_path(@gallery),class: "btn btn-warning" %>
  <% end %>
    <%= link_to 'All Galleries', galleries_path, class: "btn btn-primary" %>
  <% if admin_signed_in? %>
      <%= link_to 'Delete', @gallery, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
</p>
</p>